name: For HAMBA chat room which is check for Yangwoo buffet launch menu

on:
  schedule:
    # 한국 시간 월~목 10:11 -> UTC 월~목 01:11
    - cron: "11 1 * * Mon-Thu"
  workflow_dispatch:

jobs:
  check_posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Get current date
        id: get_date
        run: echo "TODAY=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Cache menu data
        id: cache-menu
        uses: actions/cache@v4
        with:
          path: menu_cache.json
          key: menu-data-${{ env.TODAY }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          TARGET_INSTAGRAM_ID: ${{ secrets.TARGET_INSTAGRAM_ID }}
          KAKAOWORK_WEBHOOK_URL_HAMBAROOM: ${{ secrets.KAKAOWORK_WEBHOOK_URL_FOR_HAMBA_ROOM }}
        run: python main.py --webhook-env-var KAKAOWORK_WEBHOOK_URL_HAMBAROOM
